const express = require('express')
const helmet = require('helmet')
const cors = require('cors')
const swaggerUi = require('swagger-ui-express')
const authroute = require('./routes/auth')
const userroute = require('./routes/user')
const placesroute = require('./routes/places')
const pollroute = require('./routes/poll')
const multermiddleware = require('./middlewares/multer')
const fs = require('fs')
const YAML = require('yaml')
const file = fs.readFileSync('./docs/swagger.api.docs.yaml', 'utf8')
const swaggerDocument = YAML.parse(file)
const app = express()

app.use(helmet())
app.use(cors())
app.options('*', cors())
app.use(express.json())
app.use(multermiddleware.single('photoFile'))
app.use('/v1', authroute)
app.use(express.urlencoded({ extended: true }))
app.use('/v1', userroute)
app.use('/v1', placesroute)
app.use('/v1', pollroute)
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument))
app.get('/', (req, res) => {
  res.send('Hello World!')
})

module.exports = app
