const express = require('express')
const helmet = require('helmet')
const cors = require('cors')
const swaggerJSDoc = require('swagger-jsdoc')
const swaggerUi = require('swagger-ui-express')
const authroute = require('./routes/auth')
const mlroute = require('./routes/ml.route')
const userroute = require('./routes/user')
const options = require('./config/swagger.options')
const multermiddleware = require('./middlewares/multer')
const swaggerSpec = swaggerJSDoc(options)
const app = express()

app.use(helmet())
app.use(cors())
app.options('*', cors())
app.use(express.json())
app.use(multermiddleware.single('photoFile'))
app.use('/v1', authroute)
app.use(express.urlencoded({ extended: true }))
app.use('/v1', userroute)
app.use('/v1', mlroute)
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec))
app.get('/', (req, res) => {
  res.send('Hello World!')
})

module.exports = app
