steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args: ['-c', 'sed -i "s|INSTANCE_UNIX_SOCKET:|INSTANCE_UNIX_SOCKET: $$UNIX_SOCKET|" app.yaml; sed -i "s|DB_PASS:|DB_PASS: $$PASS|" app.yaml; sed -i "s|MAPS_API_KEY:|MAPS_API_KEY: $$MAPS_KEY|" app.yaml; sed -i "s|TOKEN_SECRET:|TOKEN_SECRET: $$JWT_TOKEN|" app.yaml; sed -i "s|RECOMMENDER_API:|RECOMMENDER_API: https://hayuk-recommender-api-dae6gnqlya-et.a.run.app/recommend/|" app.yaml; sed -i "s|DEV_SERVER:|DEV_SERVER: https://dev-dot-hayuk-project.et.r.appspot.com/v1|" app.yaml; sed -i "s|DB_NAME:|DB_NAME: hayuk_api|" app.yaml; sed -i "s|DB_USER:|DB_USER: root|" app.yaml; gcloud app deploy']
    secretEnv: ['JWT_TOKEN', 'MAPS_KEY', 'UNIX_SOCKET', 'PASS']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/jwt-secret/versions/latest
      env: 'JWT_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/maps-api-key/versions/latest
      env: 'MAPS_KEY'
    - versionName: projects/$PROJECT_ID/secrets/api-db-socket/versions/latest
      env: 'UNIX_SOCKET'
    - versionName: projects/$PROJECT_ID/secrets/hayuk-recommender-api-db-pass/versions/latest
      env: 'PASS'
